Repository n8n-io/n8n-docs, pull requests merged in 2025-08, with the labels that each got.

#3390 Add Vercel AI Gateway model node
  docs/integrations/builtin/cluster-nodes/sub-nodes/n8n-nodes-langchain.lmchatvercel.md
  docs/integrations/builtin/credentials/vercel.md
  nav.yml
Labels: in-next-release

#2970 Update database-structure.md to add SAML
  docs/hosting/architecture/database-structure.md
Labels: community-contribution

#3486 add a copy of the Kapa button to the bottom of the page
  _overrides/main.html
  _overrides/partials/header.html
  _overrides/partials/kapaButton.html
  docs/_extra/css/extra.css
  docs/_extra/css/feedback.css
  docs/advanced-ai/index.md
  docs/api/api-reference.md
  docs/api/index.md
  docs/code/index.md
  docs/embed/index.md
  docs/hosting/index.md
  docs/index.md
  docs/integrations/index.md
Labels: internal-contribution

#3408 First pass on docs for workflow diffs view.
  docs/source-control-environments/using/compare-changes.md
  nav.yml
Labels: in-next-release, internal-contribution

#3418 Enhanced README file
  .gitignore
  README.md
Labels: community-contribution

#3517 docs: update Getting Started sidebar text and screenshot (fixes #3510)
  docs/_images/courses/level-one/chapter-one/l1-c1-editor-ui.png
  docs/_images/courses/level-one/chapter-one/l1-c1-side-panel.png
  docs/courses/level-one/chapter-1.md
Labels: community-contribution

#3514 docs: update canvas buttons, executions, and projects wording
  docs/_images/courses/level-one/chapter-one/l1-c1-canvas.png
  docs/courses/level-one/chapter-1.md
Labels: community-contribution

#3533 Document required headers in reverse proxy setup
  docs/hosting/configuration/configuration-examples/webhook-url.md
Labels: internal-contribution

#3528 docs: clarify Projects vs Personal project in navigation On Chapter 1
  docs/courses/level-one/chapter-1.md
Labels: community-contribution

#3543 Update chapter-1.md
  docs/courses/level-one/chapter-1.md
Labels: low-effort-usable
